### PR TITLE
Project setup

### LINKED ISSUE #64: [0.5pt] Set up the project with Webpack and Jest- Student A
- Set up Gitflow
- Set up webpack
- Set up a JavaScript testing library (Jest)

### PR DESCRIPTION
**Pull request by AnselemOdims**
# Steps
- Setup webpack and its dependencies
- Setup the linting tools
- Setup the Jest framework
- Setup Babel for transpiling of code
- Setup JSDOM for test Dom environment 

Closes #64

### CODE REVIEW

**Comment by imubarak234** [comment]
I took a look at The setup and everything looks solid.

Merge Approved 👍 💯

**Review by imubarak234 — COMMENTED** [review]
I took a look at The setup and everything looks solid.

Merge Approved 👍 💯

**Review by imubarak234 — APPROVED** [review]
I took a look at The setup and everything looks solid.

Merge Approved 👍 💯

**Comment by AnselemOdims** [comment]
Ok thanks

**Pull request merged**
